spring:
  datasource:
    url: jdbc:postgresql://172.28.83.249:5432/roomdb
    username: royra
    password: newPass3029
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      show-sql: true

  main:
    web-application-type: servlet
